.TH fatrace 8 "August 20, 2020" "Martin Pitt"

.SH NAME

fatrace \- report system wide file access events

.SH SYNOPSIS

.B fatrace
[
.I OPTIONS
]

.SH DESCRIPTION

.B fatrace
reports file access events from all running processes.

It does not report file access by fatrace itself, to avoid logging events
caused by writing the output into a file. It also ignores events on virtual and
kernel file systems such as sysfs, proc, and devtmpfs.

Its main purpose is to find processes which keep waking up the disk
unnecessarily and thus prevent some power saving.

By default, events are reported to stdout. This will cause some loops if you
run this tool in e. g. gnome-terminal, as this causes a disk access for every
output line. To avoid this, redirect the output into a file.

.SH OUTPUT FORMAT

There are two output formats. The default text format is easier on human eyes,
while the JSONL format is more suitable for automatic processing.

In text format, a typical event looks like

.RS 4
rsyslogd(875): W /var/log/auth.log
.br
compiz(1971): O device 8:2 inode 658203
.RE

In text format, the line has the following fields:

.IP \(bu 2
The current time, if you specify the
.B \-\-timestamp
option.

.IP \(bu 2
Process name. This is read from /proc/pid/comm, and might be abbreviated for
long process names.

.IP \(bu 2
Process ID

.IP \(bu 2
UID and GID, if you specify the
.B \-\-user
option.

.IP \(bu 2
Event type: \fBO\fRpen, \fBR\fRead, \fBW\fRrite, \fBC\fRlose. Events on
directories are \fB+\fR (create), \fBD\fRelete, \fB<\fR (moved from),
or \fB>\fR (moved to).
Combinations are possible, such as \fBCW\fR for closing a written file, or <>
for renaming a file within the same directory.

Directory events can only be detected on Linux 5.1 or higher.

.IP \(bu 2
Affected file. In some cases the path and name cannot be determined, e. g.
because it is a temporary file which is already deleted. In that case, it
prints the devices' major and minor number and the inode number. To examine
such a process in more detail, you should consider using
.BR strace (1).

.RE

In JSONL format, the line is a JSON-encoded object with the following fields:

.TP
.B timestamp
The current time, if you specify the
.B \-\-timestamp
option.

.TP
.B comm
Process name. This is read from /proc/pid/comm, and might be abbreviated for
long process names.

.TP
.B comm_raw
The raw bytes of the process name, in case it is not valid UTF-8.

.TP
.B pid
Process ID

.TP
.B uid
UID, if you specify the
.B \-\-user
option.

.TP
.B gid
GID, if you specify the
.B \-\-user
option.

.TP
.B types
Event type: \fBO\fRpen, \fBR\fRead, \fBW\fRrite, \fBC\fRlose. Events on
directories are \fB+\fR (create), \fBD\fRelete, \fB<\fR (moved from),
or \fB>\fR (moved to).
Combinations are possible, such as \fBCW\fR for closing a written file, or <>
for renaming a file within the same directory.

Directory events can only be detected on Linux 5.1 or higher.

.TP
.B device
device ID in
.B [major,minor]
form, if it can be determined.

.TP
.B inode
The file inode, if it can be determined.

.TP
.B path
The path to the affected file, if it can be determined.

.TP
.B path_raw
The raw bytes of the path to the affected file, in case it is not valid UTF-8.

.TP
.B problems
An array of strings describing problems that occurred while processing the events, if any.

.SH OPTIONS

.TP
.B \-c\fR, \fB\-\-current-mount
Only record events on partition/mount of current directory. Without this
option, all (real) partitions/mount points are being watched.

.TP
.B \-o \fIFILE\fR, \fB\-\-output=\fIFILE
Write events to given file instead of standard output.

.TP
.B \-s \fISECONDS\fR, \fB\-\-seconds=\fISECONDS
Stop after the given number of seconds.

.TP
.B \-t\fR, \fB\-\-timestamp
Add timestamp to events. When this option is given once, the format will be a
human readable hour:minute:second.microsecond; when given twice, the timestamp
is printed as seconds/microseconds since the epoch.

.TP
.B \-u\fR, \fB\-\-user
Add process user information to events, formatted as "[uid:gid]".

.TP
.B \-p \fIPID\fR, \fB\-\-ignore\-pid=\fIPID
Ignore events for this process ID. Can be specified multiple times.

.TP
.B \-f \fITYPES\fR, \fB\-\-filter=\fITYPES
Show only the given event types.
.B TYPES
is a list of
.BR C ", " R ", " O ", " W ", " D ", " + ", or " <
with the above meanings. < and > both mean "move" and will always enable both
directions.

E. g. use
.B \--filter=OC
to only show open and close events.

.TP
.B \-C \fICOMMAND\fR, \fB\-\-command=\fICOMMAND
Show only events for this command.

.TP
.B \-j\fR, \fB\-\-json
Write events in JSONL format (see definition above).

.TP
.B \-h \fR, \fB\-\-help
Print help and exit.

.SH AUTHOR
.B fatrace
is developed by Martin Pitt <martin@piware.de>.
