.TH fatrace 1 "February 07, 2012" "Martin Pitt"

.SH NAME

fatrace \- report system wide file access events

.SH SYNOPSIS

.B fatrace
[
.I OPTIONS
]

.SH DESCRIPTION

.B fatrace
reports file access events from all running processes. 

It does not report file access by fatrace itself, to avoid logging events
caused by writing the output into a file. It also ignores events on virtual and
kernel file systems such as sysfs, proc, and devtmpfs.

Its main purpose is to find processes which keep waking up the disk
unnecessarily and thus prevent some power saving.

By default, events are reported to stdout. This will cause some loops if you
run this tool in e. g. gnome-terminal, as this causes a disk access for every
output line. To avoid this, redirect the output into a file.

.SH OPTIONS

.TP
.B \-c\fR, \fB\-\-current-mount
Only record events on partition/mount of current directory. Without this
option, all (real) partitions/mount points are being watched.

.TP
.B \-o \fIFILE\fR, \fB\-\-output=\fIFILE
Write events to given file instead of standard output.

.TP
.B \-t \fISECONDS\fR, \fB\-\-time=\fISECONDS
Stop after the given number of seconds.

.TP
.B \-h \fR, \fB\-\-help
Print help and exit.

.SH AUTHOR
.B fatrace
is developed by Martin Pitt <martin.pitt@ubuntu.com>.

