#!/bin/sh
set -euC

USER=nobody

mkdir -m 777 tmp
trap "rm -rf tmp" EXIT INT QUIT PIPE

LOG="$AUTOPKGTEST_TMP/fatrace.log"
echo "starting fatrace..."
fatrace --current-mount --user -s 3 -o $LOG --json &
sleep 1

echo "read a file as root ..."
head NEWS > /dev/null

echo "read a file as user ..."
runuser -u $USER tail NEWS > /dev/null

echo "create/remove a file as root..."
TEST_FILE_ROOT=testroot.txt
touch "$TEST_FILE_ROOT"
rm "$TEST_FILE_ROOT"

echo "create/remove a file as usr..."
TEST_FILE_USER=tmp/test$USER.txt
runuser -u $USER touch "$TEST_FILE_USER"
runuser -u $USER rm "$TEST_FILE_USER"

echo "waiting for fatrace..."
wait

echo "checking log..."
check_log() {
    jq -e "select($1)" < $LOG > /dev/null
}

# accessing the NEWS file as root
check_log '.comm=="head" and (.types|test("^RC?O?$")) and .path=="'"$(pwd)/NEWS"'"'

# accessing the NEWS file as user
check_log '.comm=="tail" and .uid=='"$(id -u $USER)"' and .gid=='"$(id -g $USER)"' and (.types|test("^RC?O?$")) and .path=="'"$(pwd)/NEWS"'"'

# file creation as root
TEST_FILE_ROOT=$(realpath "$TEST_FILE_ROOT")
check_log '.comm=="touch" and .uid==0 and .gid==0 and (.types|test("^C?W?O$")) and .path=="'"$TEST_FILE_ROOT"'"'

TEST_FILE_USER=$(realpath "$TEST_FILE_USER")
check_log '.comm=="touch" and .uid=='"$(id -u $USER)"' and .gid=='"$(id -g $USER)"' and (.types|test("^C?W?O$")) and .path=="'"$TEST_FILE_USER"'"'
