#!/bin/sh
set -euC

LOG="$AUTOPKGTEST_TMP/fatrace.log"
echo "starting fatrace..."
fatrace --current-mount -s 2 -o $LOG --json &
sleep 1

echo "read a file..."
head NEWS > /dev/null

echo "create a file..."
TEST_FILE=test.txt
touch "$TEST_FILE"
set +C
bash -c "echo hello > '$TEST_FILE'"
set -C
rm "$TEST_FILE"

echo "moving a file within the same directory"
touch "$TEST_FILE"
mv "$TEST_FILE" "${TEST_FILE}.2"
mkdir dest
mv "${TEST_FILE}.2" dest/"${TEST_FILE}.2"
rm dest/"${TEST_FILE}.2"
rmdir dest

echo "robustness against ELOOP"
ln -s nothing link
python3 -c 'import os; os.open("link", os.RDONLY | os.NOFOLLOW)' 2>/dev/null || true
rm link

echo "waiting for fatrace..."
wait

echo "checking log..."
check_log() {
    jq -e "select($1)" < $LOG > /dev/null
}

# accessing the NEWS file
check_log '(.types|test("^RC?O?$")) and .path=="'"$(pwd)/NEWS"'"'
# file creation
TEST_FILE=$(realpath "$TEST_FILE")
check_log '.comm=="touch" and (.types|test("^C?W?O$")) and .path=="'"$TEST_FILE"'"'
check_log '.comm=="touch" and (.types|test("^C?WO?$")) and .path=="'"$TEST_FILE"'"'
check_log '.comm=="bash" and (.types|test("^C?WO?$")) and .path=="'"$TEST_FILE"'"'

# file deletion
check_log '.comm=="rm" and .types=="D" and .path=="'"$(dirname $TEST_FILE)"'"'

# dir creation
check_log '.comm=="touch" and .types=="+" and .path=="'"$(dirname $TEST_FILE)"'"'
check_log '.comm=="mkdir" and .types=="+" and .path=="'"$(dirname $TEST_FILE)"'"'

# file renaming; usually one event, but can be two
check_log '.comm=="mv" and (.types|test("^<>?$")) and .path=="'"$(dirname $TEST_FILE)"'"'
check_log '.comm=="mv" and (.types|test("^<?>$")) and .path=="'"$(dirname $TEST_FILE)"'"'

# file moving
check_log '.comm=="mv" and .types=="<" and .path=="'"$(dirname $TEST_FILE)"'"'
check_log '.comm=="mv" and .types==">" and .path=="'"$(dirname $TEST_FILE)/dest"'"'

# ELOOP ln/rm
check_log '.comm=="ln" and .types=="+" and .path=="'"$(dirname $TEST_FILE)"'"'
check_log '.comm=="rm" and .types=="D" and .path=="'"$(dirname $TEST_FILE)"'"'
