#!/bin/sh
set -euC

LOG=${AUTOPKGTEST_TMP:-/tmp}/fatrace.log
echo "starting fatrace..."
fatrace --current-mount -s 2 -o $LOG &
sleep 1

echo "read a file..."
head NEWS > /dev/null

echo "waiting for fatrace..."
wait

echo "checking log..."
check_log() {
    if ! grep -q "$1" $LOG; then
        echo "$1 not found in log:" >&2
        echo "===================" >&2
        cat $LOG >&2
        echo "===================" >&2
        exit 1
    fi
}

# accessing the NEWS file
check_log "RC\?O\? $(pwd)/NEWS$"
