#!/usr/bin/python3

# Minimal mkdir replacement for use in tests.
# By not exiting immediately, fatrace is able to gather metadata

import argparse, os, sys, time
p=argparse.ArgumentParser(add_help=False)
p.add_argument('-m', default="755")
p.add_argument('-p', action='store_true')
p.add_argument('dir')
a=p.parse_args()
os.umask(0)
os.makedirs(a.dir, mode=int(a.m, 8), exist_ok=a.p)
time.sleep(.1)
