#!/bin/sh
set -eu

MYDIR=$(dirname $(readlink -f "$0"))
export PATH=.:$PATH

for t in fatrace fatrace-currentmount; do
    export AUTOPKGTEST_TMP=$(mktemp -d)
    echo "===== $t ===="
    "$MYDIR"/$t
    rm -r "$AUTOPKGTEST_TMP"
done
